<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-LIBCCVC" failures="6" tests="25" name="TestNgLearnings" time="0.643" errors="0" timestamp="2023-07-08T18:28:45 IST">
  <testcase classname="org.example.Ex_1_Testng_basic" name="Test1" time="0.005"/>
  <testcase classname="org.example.Ex_1_Testng_basic" name="Test2" time="0.015">
    <failure type="java.lang.AssertionError" message="expected [1] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [0]
at org.example.Ex_1_Testng_basic.Test2(Ex_1_Testng_basic.java:24)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase classname="org.example.Ex_2_Testng_Annotations" name="Test1" time="0.002"/>
  <testcase classname="org.example.Ex_2_Testng_Annotations" name="Test2" time="0.006">
    <failure type="java.lang.AssertionError" message="expected [1] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [0]
at org.example.Ex_2_Testng_Annotations.Test2(Ex_2_Testng_Annotations.java:41)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase classname="org.example.Ex_2_Testng_Annotations" name="Test3" time="0.005"/>
  <testcase classname="org.example.Ex_2_Testng_Annotations" name="Test4" time="0.0"/>
  <testcase classname="org.example.Ex_2_Testng_Annotations" name="Test5" time="0.001"/>
  <testcase classname="org.example.Ex_2_Testng_Annotations" name="Test6" time="0.002"/>
  <testcase classname="org.example.Ex_3_Testng_Listner" name="Test1" time="0.008"/>
  <testcase classname="org.example.Ex_3_Testng_Listner" name="Test2" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [1] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [0]
at org.example.Ex_3_Testng_Listner.Test2(Ex_3_Testng_Listner.java:40)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase classname="org.example.Ex_4_TestngXML_basic" name="Test1" time="0.001"/>
  <testcase classname="org.example.Ex_4_TestngXML_basic" name="Test2" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [1] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [0]
at org.example.Ex_4_TestngXML_basic.Test2(Ex_4_TestngXML_basic.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase classname="org.example.Ex_5_Parameterized_Testng" name="test1" time="0.0">
    <failure type="org.testng.TestNGException" message="
Parameter &amp;apos;key1&amp;apos; is required by @Test on method test1 but has not been marked @Optional or defined
in C:\Users\Pravesh\AppData\Local\JetBrains\IdeaIC2023.1\temp-testng-customsuite.xml">
      <![CDATA[org.testng.TestNGException: 
Parameter 'key1' is required by @Test on method test1 but has not been marked @Optional or defined
in C:\Users\Pravesh\AppData\Local\JetBrains\IdeaIC2023.1\temp-testng-customsuite.xml
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="org.example.Ex_6_1_Custom_Testng_Example" name="Test1" time="0.001"/>
  <testcase classname="org.example.Ex_6_1_Custom_Testng_Example" name="Test2" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [1] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [0]
at org.example.Ex_6_1_Custom_Testng_Example.Test2(Ex_6_1_Custom_Testng_Example.java:29)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase classname="org.example.Ex_7_Testng_Groups" name="Test1" time="0.008"/>
  <testcase classname="org.example.Ex_7_Testng_Groups" name="Test2" time="0.0"/>
  <testcase classname="org.example.Ex_7_Testng_Groups" name="Test3" time="0.003"/>
  <testcase classname="org.example.Ex_7_Testng_Groups" name="Test4" time="0.001"/>
  <testcase classname="org.example.Ex_8_Testng_logs" name="Test1" time="0.002"/>
  <testcase classname="org.example.Ex_8_Testng_logs" name="Test2" time="0.002"/>
  <testcase classname="org.example.Ex_8_Testng_logs" name="Test3" time="0.004"/>
  <testcase classname="org.example.Ex_8_Testng_logs" name="Test4" time="0.004"/>
  <testcase classname="org.example.Ex_8_Testng_logs" name="Test5" time="0.003"/>
  <testcase classname="org.example.Ex_8_Testng_logs" name="Test6" time="0.003"/>
</testsuite> <!-- TestNgLearnings -->
